---
- hosts: apache

  vars_files:
    - playbooks/vars.yaml

  tasks:
    - name: Install apache
      package:
        name:
          - apache2
    - name: Enable apache {{ item }} module
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - proxy
        - proxy_http
    - name: Site file
      template:
        src: "files/resto.conf"
        dest: "/etc/apache2/sites-available/resto.conf"
        # do not rewrite - it can be changed by certbot
        force: no
        mode: 0644
      notify: Reload apache2
    - name: Site enable
      command:
        cmd: a2ensite resto.conf
        creates: /etc/apache2/sites-enabled/resto.conf
      notify: Reload apache2
    - name: Git Repository
      import_tasks: playbooks/git-repo.yaml
    - name: Documentation directory
      file:
        path: /var/www/html/doc
        state: directory
        mode: 0755
    - name: Documentation files
      copy:
        dest: /var/www/html/doc/{{ item }}
        src: /root/resto-git/docs/{{ item }}
        remote_src: true
        mode: 0644
      with_items:
        - resto-api.html
        - resto-api.json

  handlers:
    - name: Reload apache2
      service:
        name: apache2
        state: reloaded
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
