---
- hosts: apache

  vars_files:
    - playbooks/vars.yaml

  tasks:
    - name: Install apache
      package:
        name:
          - apache2
    - name: Enable apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - proxy
        - proxy_http
        - ssl
      notify: Restart apache2
    - name: Enable apache md module
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - md
      notify: Restart apache2
      when: apache_md | default(false)
    - name: MD config file
      template:
        src: "files/etc/apache2/conf-enabled/md-resto.conf"
        dest: "/etc/apache2/conf-enabled/md-resto.conf"
        mode: 0644
      notify: Reload apache2
      when: apache_md | default(false)
    - name: Site file
      template:
        src: "files/etc/apache2/sites-available/resto.conf"
        dest: "/etc/apache2/sites-available/resto.conf"
        # do not rewrite - we may want local tuning
        force: no
        mode: 0644
      notify: Reload apache2
    - name: SSL protocols config file
      template:
        src: "files/etc/apache2/conf-available/ssl-protocols.conf"
        dest: "/etc/apache2/conf-available/ssl-protocols.conf"
        mode: 0644
      notify: Reload apache2
    - name: SSL protocols config enable
      command:
        cmd: a2enconf ssl-protocols
        creates: /etc/apache2/conf-enabled/ssl-protocols.conf
      notify: Reload apache2
    - name: Site enable
      command:
        cmd: a2ensite resto.conf
        creates: /etc/apache2/sites-enabled/resto.conf
      notify: Reload apache2
    - name: Default site disable
      command:
        cmd: a2dissite 000-default
        removes: /etc/apache2/sites-enabled/000-default.conf
    - name: Git Repository
      import_tasks: playbooks/git-repo.yaml

  handlers:
    - name: Reload apache2
      service:
        name: apache2
        state: reloaded
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
