---
- hosts: resto
  tasks:
    - name: Install docker
      package:
        name:
          - docker.io
          - docker-compose
          - postgresql-client
    - name: Config docker MTU
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "mtu": {{ mtu }}
          }
      notify: Reload docker
    - name: Git checkout
      git:
        # https://github.com/jjrom/resto, master
        repo: https://github.com/valtri/resto
        dest: /root/resto-git
        clone: yes
        update: no
        version: cesnet
    - name: Config
      vars:
        fip_hostname: "{{ lookup('dig', groups['fip'][0] + '/PTR') | regex_replace('\\.$', '') }}"
        endpoint_hostname: "{{ public_hostname | default(fip_hostname) }}"
      block:
        - name: Config strings
          vars:
            config:
              PUBLIC_ENDPOINT: "http://{{ endpoint_hostname }}:5252"
              ADMIN_USER_PASSWORD: "{{ secret_admin_password }}"
              JWT_PASSPHRASE: "{{ secret_jwt_passphrase }}"
              SENDMAIL_SENDER_EMAIL: "noreply@{{ fip_hostname }}"
              SENDMAIL_SMTP_HOST: "{{ smtp_host }}"
              SENDMAIL_SMTP_PORT: "{{ smtp_port }}"
              # problem with CA certificates in containers (requires changes in resto app)
              SENDMAIL_SMTP_SECURE: "none"
          lineinfile:
            path: /root/resto-git/config.env
            regexp: '^[ #]*{{ item.key }}\s*=.*'
            line: "{{ item.key }}=\"{{ item.value }}\""
          loop: "{{ config | dict2items }}"
          notify: Reconfigure resto
        - name: Config non-strings
          vars:
            config:
              SENDMAIL_SMTP_ACTIVATE: "true"
              SENDMAIL_SMTP_DEBUG: "1"
              USER_AUTOACTIVATION: "false"
          lineinfile:
            path: /root/resto-git/config.env
            regexp: '^[ #]*{{ item.key }}\s*=.*'
            line: "{{ item.key }}={{ item.value }}"
          loop: "{{ config | dict2items }}"
          notify: Reconfigure resto

  handlers:
    - name: Reconfigure resto
      debug:
        msg: "Launch manually: cd ~/resto-git && ./deploy prod"
    - name: Reload docker
      service:
        name: docker
        state: restarted
